### PR TITLE
Update Tabzilla (Fix #7)

### LINKED ISSUE #7: Upgrade tabzilla
This fall, Mozilla released a new version of Tabzilla: https://github.com/mozilla/tabzilla

This version is static and easier to integrate and maintain. I may contribute a fix.

### PR DESCRIPTION
**Pull request by ferndot**

### CODE REVIEW

**Comment by Mte90** [comment]
the tabzilla.css is missing as a wordpress template for an easy installation i think that we have to include on the repo.

Thx for the pr!

**Comment by ferndot** [comment]
So, Tabzilla doesn't need to be included in this repo?

**Comment by Mte90** [comment]
Need to be included but the tabzilla.css is missing in that pr and you have removed the js.
So to generate the tabzilla we need to add something

**Comment by Mte90** [comment]
I have refactored all the theme without the tabzilla so in this way we can evaluate the best option.

**Comment by ferndot** [comment]
I think that the tabzilla css is included when you run `npm install`.

**Pull request closed without merging**
